name: Semantic release 

on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.6.1
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install 
      - name: Build app
        run: npm run build 
      - name: Publish app1
        run: npm ci
      - name: Publish app2
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
